### PR TITLE
Endoc 1 reorg

### PR DESCRIPTION
**Pull request by nshaw**

### CODE REVIEW

**Comment by nshaw** [comment]
Reviewers, this is not quite ready to merge since several PRs have been merged to master lately and we need your help to make sure they land in the new structure. You can find some details in the new JIRA project under https://jira.entando.org/browse/ENDOC-1 or feel free to slack me or Ed. We haven't communicated this to Engineering enough, I think, but we are moving from docs.entando.com to dev.entando.org and splitting the documentation into docs and tutorials sections (eventually, dev.entando.org/docs and dev.entando.org/tutorials). You can see a slightly out-of-date version of this on Ed's Github Pages at https://es-entando.github.io/ - it doesn't include the master rebase/reorg work I did today yet. 

Our hope is to polish this up in the next day or so and get this new structure published in time for the new web site release on Friday 6/12. If we need a meeting to discuss anything specific, please let me know or add as many comments as you want here.

Thanks,
Nathan

**Comment by es-entando** [comment]
Looks good.

**Comment by joewhite101** [comment]
Looks good to me based on review of published content at es-entando.github.io

**Comment by nshaw** [comment]
> The entando.yaml file you've added here includes the PDA plugin. I don't think we should be including that. It won't work unless there is a PAM instance also installed somewhere. I think you'll need to update or roll back to a 6.1.1 deployment.

Thanks. I'm on it. There's a duplicate entando.yaml at the root that I thought was in use so I'll clean that up too.

**Pull request merged**
