### PR TITLE
Endoc-367 Fix links in Custom Resources

### PR DESCRIPTION
**Pull request by jyunmitch**
Fixed links in v6.3.2 custom-resources.md, next custom-resources.md and added text to Readme.md for Versions. I am unsure about the txt in the readme.

### CODE REVIEW

**Comment by Lyd1aCla1r3** [comment]
I like your readme comment :) maybe use lowercase for custom-resources.md for consistency?

**Comment by nshaw** [comment]
> I like your readme comment :) maybe use lowercase for custom-resources.md for consistency?

I'm with Lydia, lowercase the reference (since Linux is definitely case-sensitive when it comes to file names) and we're good to go.

**Review by nshaw — CHANGES_REQUESTED** [review]
Minor change as noted

**Comment by jyunmitch** [comment]
thanks. You're right, don't know why I cap those. I guess old habits.

**Comment by jyunmitch** [comment]
done

**Review by nshaw — APPROVED** [review]

**Pull request merged**
