### PR TITLE
ENDOC-412b Solution Templates landing page

### PR DESCRIPTION
**Pull request by Lyd1aCla1r3**

### CODE REVIEW

**Review by nshaw — CHANGES_REQUESTED** [review]
Couple links to fix but looks good other than that.

**Comment by Lyd1aCla1r3** [comment]
@nshaw the broken links are the hub url that's not live yet; i think you wanted to change to this from the dev placeholder?

**Comment by nshaw** [comment]
> @nshaw the broken links are the hub url that's not live yet; i think you wanted to change to this from the dev placeholder?

I think you need to include the protocol to fix the link checker - https://hub.entando.com instead of just hub.entando.com.

**Review by nshaw — APPROVED** [review]

**Comment by nshaw** [comment]
@jyunmitch should we merge this now or hold while you're getting the nav in place for 6.3.2? I'd lean towards merging it but we don't want to lose track it needs to be added to 6.3.2 once your 2nd round of refactoring is done.

**Comment by Lyd1aCla1r3** [comment]
@nshaw let's go ahead and merge. i made a note to get this into 6.3.2 whenever @jyunmitch gives me the green light

**Comment by nshaw** [comment]
Sounds good to me.

**Pull request merged**
