### PR TITLE
ENG-1265 updates labels, groups, categories, languages, contents, assets and pages documentation

### PR DESCRIPTION
**Pull request by Kerruba**

### CODE REVIEW

**Comment by nshaw** [comment]
Hey, @Kerruba. Is this PR still in progress? It's marked as Draft but it's been open a few days.

**Comment by Kerruba** [comment]
@nshaw yeah it is, we are waiting for some work done by @ffleandro on other type of components to be included in this to make a single PR instead of multiple ones

**Comment by nshaw** [comment]
@Kerruba , very good, thanks for the update.

**Comment by joewhite101** [comment]
@ffleandro is this still on your radar?

@nshaw once we merge this one we'll have diverged from 6.2. These components won't be available there.

**Comment by ffleandro** [comment]
It is, the plan is to first finish all of the development related to this and then update de docs.

**Comment by nshaw** [comment]
> @ffleandro is this still on your radar?
> 
> @nshaw once we merge this one we'll have diverged from 6.2. These components won't be available there.

@joewhite101 Yep, I figured. We have a few pages like that so I'm watching for those differences when syncing next to 6.2. Since we chose to make the next release 6.3 instead of 6.2.1 I'm guessing we'll want to add a new 6.3 version to the docs site but that still needs to be discussed.

**Comment by nshaw** [comment]
@Kerruba , any ETA on this one?

**Comment by nshaw** [comment]
I'm looking at entando-component-manager/src/main/java/org/entando/kubernetes/model/bundle/ComponentType.java and it appears we have a few more types still to document, e.g. asset, language, page, content, directory(?).

**Comment by ffleandro** [comment]
Yes Nathan, this is still a work in progress, but we definitely need to update the documentation before release of 6.3.0

**Comment by ffleandro** [comment]
Will start working on this today!

**Comment by ffleandro** [comment]
@nshaw this is ready for review!

**Comment by ffleandro** [comment]
@nshaw have you reviewed this?

**Comment by nshaw** [comment]
> @nshaw have you reviewed this?

Yep, my PR was to adjust the language and organization a bit. LGTM now.

**Review by nshaw — APPROVED** [review]

**Pull request merged**
