### PR TITLE
ENG-1370 retrocompatible installation old plugin descriptor + ENG-1380 deploymentBaseName

### PR DESCRIPTION
**Pull request by firegloves**

### CODE REVIEW

**Review by w-caffiero-entando — CHANGES_REQUESTED** [review]
@firegloves @nshaw I propose to not document the old version at all.

It's deprecated (users shouldn't use it) and it's currently supported only for compatibility with  descriptors contained in already existing bundles.

**Comment by nshaw** [comment]
> @firegloves @nshaw I propose to not document the old version at all.
> 
> It's deprecated (users shouldn't use it) and it's currently supported only for compatibility with descriptors contained in already existing bundles.

That makes sense to me unless there's a compelling reason to document it for current clients. If that's the case I'd suggest we add this just to the 6.2 version of the docs and mark it deprecated. I suspect we'll be cutting the 6.3 version of the docs soon and we could leave it out there.  @firegloves , @w-caffiero-entando , thoughts?

**Comment by firegloves** [comment]
@nshaw @w-caffiero-entando may be an option to place a line like this?
"the previous plugin descriptor version is now deprecated. It's still supported but we encourage you to migrate to the newer version"

**Comment by nshaw** [comment]
There's a product question whether we actually plan to support it. I'd favor documenting it for 6.2 as Deprecated but not include it in next/6.3. I can make that change if @w-caffiero-entando is okay with the approach.

**Comment by w-caffiero-entando** [comment]
> I'd favor documenting it for 6.2 as Deprecated but not include it in next/6.3. I can make that change if @w-caffiero-entando is okay with the approach.

Uhm, on 6.2 can't be deprecated as it's the only version supported.

I'm fine keeping it on 6.3 but deprecated, but I'd prefer to keep on the main page only the new one and plus link to the deprecated version.

**Comment by nshaw** [comment]
Thanks for clarifying. I misunderstood that part. We should probably call that out in the Release Notes then since it could be a breaking change in 6.4.

**Comment by w-caffiero-entando** [comment]
> Thanks for clarifying. I misunderstood that part. We should probably call that out in the Release Notes then since it could be a breaking change in 6.4.

Agree

**Comment by nshaw** [comment]
@w-caffiero-entando , @firegloves I updated this with the deprecation warnings. Visible at https://entando.github.io/entando-docs/next/docs/ecr/ecr-bundle-details.html#plugin-descriptor and https://entando.github.io/entando-docs/v6.2/docs/ecr/ecr-bundle-details.html#plugin-descriptor.

**Review by nshaw — APPROVED** [review]

**Comment by firegloves** [comment]
I added some docs for ENG-1380

**Review by w-caffiero-entando — APPROVED** [review]

**Pull request merged**
